### Criar Conta Corrente
POST http://localhost:3000/contas
Content-Type: application/json

{
  "id": "1",
  "clientId": "1",
  "type": "corrente",
  "balance": 1000,
  "dailyWithdrawalLimit": 500,
  "monthlyServiceFee": 10,
  "overdraftLimit": 100
}

### Criar Conta Poupança
POST http://localhost:3000/contas
Content-Type: application/json

{
  "id": "2",
  "clientId": "1",
  "type": "poupanca",
  "balance": 2000,
  "interestRate": 5
}

### Depositar em Conta Corrente
POST http://localhost:3000/contas/1/depositar
Content-Type: application/json

{
  "amount": 500
}

### Sacar de Conta Corrente
POST http://localhost:3000/contas/1/sacar
Content-Type: application/json

{
  "amount": 200
}

### Transferir de Conta Corrente para Conta Poupança
POST http://localhost:3000/contas/1/transferir
Content-Type: application/json

{
  "destinationAccountId": "2",
  "amount": 300
}

### Consultar Saldo
GET http://localhost:3000/contas/1/saldo

### Gerar Extrato
GET http://localhost:3000/contas/1/extrato

